name: llama-writes-story

on:
  workflow_dispatch: {}  # run manually from the Actions tab

permissions:
  contents: write  # so the job can commit the story

jobs:
  generate-story:
    runs-on: ubuntu-latest  # CPU-only runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ollama CLI
        uses: ai-action/setup-ollama@v1

      - name: Cache Ollama models (speeds up subsequent runs)
        uses: actions/cache@v4
        with:
          path: ~/.ollama
          key: ${{ runner.os }}-ollama
          restore-keys: |
            ${{ runner.os }}-ollama
      # Run llama 3.2 3B and save ONLY the model output to a file.
      - name: Generate story with llama3.2:3b (CPU)
        env:
          # Keep the prompt outside the file so the saved story text is 100% AI-authored.
          PROMPT: |
            Write an original, self-contained short story (200–300 words).
            Requirements:
            - No preface or explanation; output ONLY the story text.
            - Give it a title on the first line, then a blank line, then the story.
            - Literary but readable.
            - Fresh plot; no copyrighted characters or settings.
            - Crossdressing theme.
            - Mention the word "thong", "erection", "mini skirt".
        run: |
          set -euo pipefail
          mkdir -p stories
          FILE="stories/story-$(date -u +%Y%m%d-%H%M%SZ).md"
          # Pull once (cached across runs) and generate
          ollama pull llama3.2:3b
          # Write only the model's response to the file (no wrappers)
          ollama run llama3.2:3b "$PROMPT" > "$FILE"
          # Sanity check: ensure the file isn't empty
          test -s "$FILE"

      - name: Commit & push the AI-written story
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add stories/*.md
          git commit -m "AI story by llama3.2:3b on $(date -u +%Y-%m-%dT%H:%M:%SZ)" || exit 0
          git push
