name: Scan new Hansard transcripts (by current year)

on:
  # Run manually when you want to test
  workflow_dispatch: {}
  # Run daily 5pm Hobart (AEST=UTC+10 → 07:00 UTC). Adjust as needed.
  schedule:
    - cron: "0 7 * * *"

permissions:
  contents: write

concurrency:
  group: hansard-scan
  cancel-in-progress: false

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m playwright install chromium
          
      - name: Setup Ollama CLI
        uses: ai-action/setup-ollama@v1

      - name: Cache Ollama models
        uses: actions/cache@v4
        with:
          path: ~/.ollama
          key: ${{ runner.os }}-ollama
          restore-keys: |
            ${{ runner.os }}-ollama

      - name: Pull Llama 3.2 3B
        run: ollama pull llama3.2:3b


      - name: Scan & download any new transcripts for current year
        env:
          WAIT_BEFORE_DOWNLOAD_SECONDS: "15"
          MAX_PAGES: "1"
          HOUSE_PREFIX: "House of Assembly"
        run: python scan_new_transcripts.py

      - name: Commit new transcripts (if any)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add transcripts/*.txt || echo "No transcripts"
          git commit -m "New transcripts (auto)" || echo "No changes"
          git push

      - name: Send keyword digest email
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO:   ${{ secrets.EMAIL_TO }}
          ATTRIB_WITH_LLM: "1"            # <-- add
          ATTRIB_LLM_MODEL: "llama3.2:3b" # <-- add (optional; default is same)
        run: python send_email.py

      - name: Commit sent log
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add sent.log || echo "No log"
          git commit -m "Update sent log (auto)" || echo "No changes"
          git push
